# appveyor.yml
version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache:
  directories:
    - node_modules  # кеширование

install:
  - npm ci  # команда установки зависимостей с учетом package-lock.json

build:
  project: false  # Указывает, что вы не используете проект Visual Studio
  script:
    - npm run build  # Ваша команда сборки

test_script:
  - npm run lint & npm test  # параллельное выполнение линтинга и тестов